// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYyG9FpRUPY23V6PZ0pe0_PLYjkaN7yqE',
    appId: '1:453576168633:web:b3f76cdaab01f8854b3768',
    messagingSenderId: '453576168633',
    projectId: 'zomato-4838f',
    authDomain: 'zomato-4838f.firebaseapp.com',
    storageBucket: 'zomato-4838f.firebasestorage.app',
    measurementId: 'G-QLQB20X0H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRthetpEustTwj1me0MkrL5KwUKZG4Io',
    appId: '1:453576168633:android:297fc89f24efd5b44b3768',
    messagingSenderId: '453576168633',
    projectId: 'zomato-4838f',
    storageBucket: 'zomato-4838f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgDuIBg2nAdTrh0CdsA1Ta4yxR9lCkPc',
    appId: '1:453576168633:ios:b7c06f4ea6a0e0904b3768',
    messagingSenderId: '453576168633',
    projectId: 'zomato-4838f',
    storageBucket: 'zomato-4838f.firebasestorage.app',
    iosBundleId: 'com.example.zomatoUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgDuIBg2nAdTrh0CdsA1Ta4yxR9lCkPc',
    appId: '1:453576168633:ios:b7c06f4ea6a0e0904b3768',
    messagingSenderId: '453576168633',
    projectId: 'zomato-4838f',
    storageBucket: 'zomato-4838f.firebasestorage.app',
    iosBundleId: 'com.example.zomatoUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYyG9FpRUPY23V6PZ0pe0_PLYjkaN7yqE',
    appId: '1:453576168633:web:7c4ff21eff4086304b3768',
    messagingSenderId: '453576168633',
    projectId: 'zomato-4838f',
    authDomain: 'zomato-4838f.firebaseapp.com',
    storageBucket: 'zomato-4838f.firebasestorage.app',
    measurementId: 'G-FZRY4LJ8FN',
  );
}
